Script "stack_rTreeEngine_card_id_2226"

/*
# Name: card "Images" of stack "rTreeEngine" of stack "livecodeTestInterface"
# ID: card id 2226 of stack "rTreeEngine" of stack "livecodeTestInterface"
# Hash: Y1coEzTpn31ci9hKUYVdnA==
*/


on resizeStack
   set the ResizedRectangle of me to the rectangle of this stack
end resizeStack

on moveStack
   set the ResizedRectangle of me to the rectangle of this stack
end moveStack
