Script "stack_rTreeEngine_group_id_2864"

/*
# Name: group "Script Editor" of card "Images" of stack "rTreeEngine" of stack "livecodeTestInterface"
# ID: group id 2864 of card id 2226 of stack "rTreeEngine" of stack "livecodeTestInterface"
# Hash: VANzOP19GA+V4VDThB3NUg==
*/


on mouseEnter
  set the tooltip of the target to the id of the target
end mouseEnter

on mouseLeave
  set the tooltip of the target to empty
end mouseLeave
