Script "stack_livecodeTestInterface_field_id_31140"

/*
# Name: field "testFilter" of card "main" of stack "livecodeTestInterface"
# ID: field id 31140 of card id 1002 of stack "livecodeTestInterface"
# Hash: 3hnBe8U46449nMm8RTGS2A==
*/


on enterInField
   testList the text of me
end enterInField

on returnInField
   testList the text of me
end returnInField

--on textChanged
--   testList the text of me
--end textChanged
