Script "stack_revPreferencesGUI_button_id_1251"

/*
# Name: button "DBQueryBuilder" of group "Unsupported Features" of group "Compatibility" of card "Compatibility" of stack "revPreferencesGUI"
# ID: button id 1251 of group id 1250 of group id 1241 of card id 1015 of stack "revPreferencesGUI"
# Hash: 3ERlj34tH1KDVp6JfBzZpA==
*/


on mouseUp
   revIDEPrefSet "Unsupported,EnableDBQueryBuilder", the hilite of me
end mouseUp
