Script "stack_revPreferencesGUI_button_id_1049"

/*
# Name: button "Don't remove" of group id 1046 of group "Closing Stacks" of group "Files & Memory" of card "Files & Memory" of stack "revPreferencesGUI"
# ID: button id 1049 of group id 1046 of group id 1043 of group id 1041 of card id 1007 of stack "revPreferencesGUI"
# Hash: sP2jLOa3zK0ZYB5togUneQ==
*/


on mouseUp
  set the cASKDestroy of stack "revPreferences" to "don't remove"
end mouseUp
