Script "stack_revPreferencesGUI_field_id_1030"

/*
# Name: field "external editor" of group id 1029 of group "General" of card "General" of stack "revPreferencesGUI"
# ID: field id 1030 of group id 1029 of group id 1016 of card id 1002 of stack "revPreferencesGUI"
# Hash: W7IkJEqcZE98nzx3o9p0Xw==
*/


on closeField
  set the § of stack "revPreferences" to the text of fld "external editor"
end closeField
