Script "stack_revPreferencesGUI_button_id_1056"

/*
# Name: button "Preserve Stack Creator" of group "Stack File Property Preservation" of group "Files & Memory" of card "Files & Memory" of stack "revPreferencesGUI"
# ID: button id 1056 of group id 1055 of group id 1041 of card id 1007 of stack "revPreferencesGUI"
# Hash: 8O8kh26ApQc/McaZ8iW6FQ==
*/


on mouseUp
  set the cPreserveStackCreator of stack "revPreferences" to the hilite of me
end mouseUp
