Script "stack_revPreferencesGUI_button_id_1057"

/*
# Name: button "Preserve Stack Version" of group "Stack File Property Preservation" of group "Files & Memory" of card "Files & Memory" of stack "revPreferencesGUI"
# ID: button id 1057 of group id 1055 of group id 1041 of card id 1007 of stack "revPreferencesGUI"
# Hash: 5mYcjWACNY2gAeOVbWBioQ==
*/


on mouseUp
  set the cPreserveStackVersion of stack "revPreferences" to the hilite of me
end mouseUp
