Script "stack_revPreferencesGUI_button_id_1021"

/*
# Name: button "navigation arrows" of group "Shortcuts" of group "General" of card "General" of stack "revPreferencesGUI"
# ID: button id 1021 of group id 1019 of group id 1016 of card id 1002 of stack "revPreferencesGUI"
# Hash: GQG7JratLtf+Zv/6uWel7g==
*/


on mouseUp
  set the navigationArrows to the hilite of me
  set the cNavigationArrows of stack "revPreferences" to the hilite of me
end mouseUp
