Script "stack_revPreferencesGUI_button_id_1047"

/*
# Name: button "Remove from memory" of group id 1046 of group "Closing Stacks" of group "Files & Memory" of card "Files & Memory" of stack "revPreferencesGUI"
# ID: button id 1047 of group id 1046 of group id 1043 of group id 1041 of card id 1007 of stack "revPreferencesGUI"
# Hash: qkqwSB3DmukcAmfc4m1Exw==
*/


on mouseUp
  set the cASKDestroy of stack "revPreferences" to "remove"
end mouseUp
