Script "stack_revPreferencesGUI_button_id_1044"

/*
# Name: button "destroyStack" of group "Closing Stacks" of group "Files & Memory" of card "Files & Memory" of stack "revPreferencesGUI"
# ID: button id 1044 of group id 1043 of group id 1041 of card id 1007 of stack "revPreferencesGUI"
# Hash: WOq7/ExIgAseS42xB0cLRw==
*/


on mouseUp
  set the cDestroyStack of stack "revPreferences" to the hilite of me
end mouseUp
