Script "stack_com.livecode.pi.point_field_id_1008"

/*
# Name: field "y" of group "template" of card id 1002 of stack "com.livecode.pi.point"
# ID: field id 1008 of group id 1004 of card id 1002 of stack "com.livecode.pi.point"
# Hash: CsiUzfnnwOmFJ5GGqtpBRw==
*/


on returnInField
   dispatch "valueChanged"
end returnInField

on enterInField
   dispatch "valueChanged"
end enterInField

on closeField
   dispatch "valueChanged"
end closeField
