Script "stack_com.livecode.pi.customprops_button_id_1014"

/*
# Name: button "customPropertySet" of group "Set buttons" of group "template" of card id 1002 of stack "com.livecode.pi.customprops"
# ID: button id 1014 of group id 1012 of group id 1004 of card id 1002 of stack "com.livecode.pi.customprops"
# Hash: ZBJRJXzKqmBWfzGUrRKOiQ==
*/


on menuPick pWhich
   dispatch "propSetSelected" with pWhich
end menuPick
