Script "stack_com.livecode.pi.dimension_field_id_1003"

/*
# Name: field "Field" of group "template" of card id 1002 of stack "com.livecode.pi.dimension"
# ID: field id 1003 of group id 1004 of card id 1002 of stack "com.livecode.pi.dimension"
# Hash: CsiUzfnnwOmFJ5GGqtpBRw==
*/


on returnInField
   dispatch "valueChanged"
end returnInField

on enterInField
   dispatch "valueChanged"
end enterInField

on closeField
   dispatch "valueChanged"
end closeField
