Script "stack_revGettingStartedScripts_bkgnd_id_1156"

/*
# Name: bkgnd "Getting the dimensions of a picture file Example" of stack "revGettingStartedScripts"
# ID: bkgnd id 1156 of stack "revGettingStartedScripts"
# Hash: jeMAFJ1ujkoA7dGOqTUTSg==
*/


on preOpenBackground
  put empty into field "Filename"
  put "??" into word 2 of field "Height"
  put "??" into word 2 of field "Width"
end preOpenBackground
