Script "stack_revGettingStartedScripts_button_id_1069"

/*
# Name: button "Center Me!" of group "Centering a window on the screen Example" of card id 1002 of stack "revGettingStartedScripts"
# ID: button id 1069 of group id 1068 of card id 1002 of stack "revGettingStartedScripts"
# Hash: rr4lPlTAayqWqSBkvWgjmg==
*/


on mouseUp
  centerMe
end mouseUp

on centerMe
  set the loc of this stack to the screenLoc
end centerMe
