Script "stack_revGettingStartedScripts_group_id_1101"

/*
# Name: group "Converting an absolute path to a relative path Example" of card id 1002 of stack "revGettingStartedScripts"
# ID: group id 1101 of card id 1002 of stack "revGettingStartedScripts"
# Hash: ArR2XEyLWrITzux78kclDg==
*/


on preOpenBackground
  put empty into field "Path"
  put the defaultFolder into field "Starting Folder"
end preOpenBackground
