Script "stack_revGettingStartedScripts_group_id_1110"

/*
# Name: group "Converting between characters and numerical (ASCII) values Example" of card id 1002 of stack "revGettingStartedScripts"
# ID: group id 1110 of card id 1002 of stack "revGettingStartedScripts"
# Hash: R/gwcgFbpPVyyiMkJhaLVg==
*/


on returnInField
  enterInField
end returnInField

on enterInField
  send "mouseUp" to button "Convert"
end enterInField
