Script "stack_revGettingStartedScripts_group_id_1092"

/*
# Name: group "Converting a relative path to an absolute path Example" of card id 1002 of stack "revGettingStartedScripts"
# ID: group id 1092 of card id 1002 of stack "revGettingStartedScripts"
# Hash: ArR2XEyLWrITzux78kclDg==
*/


on preOpenBackground
  put empty into field "Path"
  put the defaultFolder into field "Starting Folder"
end preOpenBackground
