Script "stack_revGettingStartedScripts_group_id_1141"

/*
# Name: group "Finding lines that are not common to two containers Example" of card id 1002 of stack "revGettingStartedScripts"
# ID: group id 1141 of card id 1002 of stack "revGettingStartedScripts"
# Hash: /qlN8MJGEOZeGB4uvPNHeQ==
*/


on preOpenBackground
  put the initialText of field "List 1" into field "List 1"
  put the initialText of field "List 2" into field "List 2"
end preOpenBackground
