Script "stack_revGettingStartedScripts_button_id_1058"

/*
# Name: button "Window" of group "Menubar" of group "Updating a menu with a list of open Windows Example" of card id 1002 of stack "revGettingStartedScripts"
# ID: button id 1058 of group id 1057 of group id 1055 of card id 1002 of stack "revGettingStartedScripts"
# Hash: z2Cj1WSjjCy76Twp014AJA==
*/


on menuPick theItem
  answer "You chose:" & return & tab & theItem
end menuPick 
