Script "stack_revGettingStartedScripts_group_id_1019"

/*
# Name: group "Link text roll over effect Example" of card id 1002 of stack "revGettingStartedScripts"
# ID: group id 1019 of card id 1002 of stack "revGettingStartedScripts"
# Hash: USFuqsnA35Lr3FXClOepng==
*/


on mouseLeave
  -- block the general documentation handlers
end mouseLeave

on mouseEnter
  -- block the general documentation handlers
end mouseEnter

on mouseMove
  -- block the general documentation handlers
end mouseMove
