Script "stack_revGettingStartedScripts_scrollbar_id_1228"

/*
# Name: scrollbar "Green" of group "Setting an RGB color channel of an object Example" of card id 1002 of stack "revGettingStartedScripts"
# ID: scrollbar id 1228 of group id 1223 of card id 1002 of stack "revGettingStartedScripts"
# Hash: f4dBtaGLxtng4F86DDazWw==
*/


on scrollbarDrag newPosition
  set the greenChannel of graphic "Color Swatch" to newPosition
end scrollbarDrag
