Script "stack_revGettingStartedScripts_scrollbar_id_1229"

/*
# Name: scrollbar "Blue" of group "Setting an RGB color channel of an object Example" of card id 1002 of stack "revGettingStartedScripts"
# ID: scrollbar id 1229 of group id 1223 of card id 1002 of stack "revGettingStartedScripts"
# Hash: xZ8+axzVoltgnlVrIawAYA==
*/


on scrollbarDrag newPosition
  set the blueChannel of graphic "Color Swatch" to newPosition
end scrollbarDrag
