Script "stack_revGettingStartedScripts_group_id_1059"

/*
# Name: group "Repeating a string of text Example" of card id 1002 of stack "revGettingStartedScripts"
# ID: group id 1059 of card id 1002 of stack "revGettingStartedScripts"
# Hash: 28BnRlynbTLUCYQtcL8Aqg==
*/


on preOpenBackground
  put empty into field "String"
  put empty into field "Number"
  put empty into field "Result"
end preOpenBackground
