Script "stack_revMenuDialog_button_id_1008"

/*
# Name: button "OK" of card id 1002 of stack "revMenuDialog" of stack "revMenuManager"
# ID: button id 1008 of card id 1002 of stack "revMenuDialog" of stack "revMenuManager"
# Hash: bLuW8c9kL5fWOAB9/DFjtg==
*/


# OK-2007-09-25 : Refactored code to card script to prevent nasty stuff like "click at the loc of button..."
on mouseUp
  closeAccept
end mouseUp


