Script "stack_revStartCenter_button_id_2138"

/*
# Name: button "socialBehavior" of card "interface" of stack "revStartCenter"
# ID: button id 2138 of card id 1002 of stack "revStartCenter"
# Hash: FDpV920DzsGpQITfJSpI3g==
*/


on mouseUp
   startCenterAction the short name of me
end mouseUp

on mouseEnter
   socialMediaHilite the short name of me, true
end mouseEnter

on mouseLeave
   socialMediaHilite the short name of me, false
end mouseLeave
