Script "stack_com.livecode.pi.geometry_graphic_id_1056"

/*
# Name: graphic "Top object" of group "Top Object" of group "content" of group "Diagram" of group "template" of card "revGeometryScale" of stack "com.livecode.pi.geometry"
# ID: graphic id 1056 of group id 1014 of group id 1080 of group id 1063 of group id 1065 of card id 1003 of stack "com.livecode.pi.geometry"
# Hash: aLMp2piT40CZx9itXLnJQA==
*/



