Script "stack_File_Attribs_button_id_1303"

/*
# Name: button "Enter Password 3" of card "Question Answer Password" of stack "File Attribs"
# ID: button id 1303 of card id 1138 of stack "File Attribs"
# Hash: D0/ghIEo42QNTW+WWzx5/A==
*/


on mouseUp
   ask password "Please log in and provide your passwod:" with "qwert" titled "Password Test number three with double lines"
   put it into field "Password" 
end mouseUp
