Script "stack_File_Attribs_group_id_1283"

/*
# Name: group id 1283 of card "Clear Touches" of stack "File Attribs"
# ID: group id 1283 of card id 1272 of stack "File Attribs"
# Hash: 0rMLT4xO3jg0LRstx0DQGg==
*/


on mouseDown
   put the params & return after field "Log"
end mouseDown

on mouseUp
   put the params & return after field "Log"
end mouseUp

on touchStart
   put the params & return after field "Log"
end touchStart

on touchEnd
   put the params & return after field "Log"
end touchEnd
