Script "stack_com.livecode.pi.gradientramp_scrollbar_id_1014"

/*
# Name: scrollbar "alpha" of group id 1013 of group "color" of group "template" of card id 1002 of stack "com.livecode.pi.gradientramp"
# ID: scrollbar id 1014 of group id 1013 of group id 1012 of group id 1008 of card id 1002 of stack "com.livecode.pi.gradientramp"
# Hash: mfzH1MQLDCACb9BTkNhbTw==
*/


on scrollbarDrag
   dispatch "valueChanged"
end scrollbarDrag
