Script "stack_revDataViewControl_button_id_1005"

/*
# Name: button "VScrollbar Behavior" of card id 1002 of stack "revDataViewControl" of stack "revCore"
# ID: button id 1005 of card id 1002 of stack "revDataViewControl" of stack "revCore"
# Hash: qFS0w0DoAGu7O6ppJAekyg==
*/


## scrollbarDrag is handled in the main control behavior

on dragStart
   ## Scrollbars don't need to send dragStart messages
end dragStart
