Script "stack_revIDEExtensionManager_group_id_39494"

/*
# Name: group "installProgress" of group "extensionRow" of group "dvList" of group "dvListMask" of group "extensionList" of card "list" of stack "revIDEExtensionManager"
# ID: group id 39494 of group id 39487 of group id 1008 of group id 1007 of group id 1003 of card id 1002 of stack "revIDEExtensionManager"
# Hash: Un73vMAkfs2RGVikyyYQWw==
*/


on resizeControl
   set the width of scrollbar "installProgressBar" of me to the width of me
   set the width of field "installProgressStatus" of me to the width of me
   
   set the right of scrollbar "installProgressBar" of me to the right of me
   set the right of field "installProgressStatus" of me to the right of me
end resizeControl
