Script "stack_com.livecode.pi.script_field_id_1008"

/*
# Name: field "Field" of group "template" of card id 1002 of stack "com.livecode.pi.script"
# ID: field id 1008 of group id 1007 of card id 1002 of stack "com.livecode.pi.script"
# Hash: CsiUzfnnwOmFJ5GGqtpBRw==
*/


on returnInField
   dispatch "valueChanged"
end returnInField

on enterInField
   dispatch "valueChanged"
end enterInField

on closeField
   dispatch "valueChanged"
end closeField
