Script "stack_revStandaloneSettings_button_id_31492"

/*
# Name: button "Icon Chooser" of group "AppStore Icon" of group "Icons" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 31492 of group id 31490 of group id 3494 of card id 1641 of stack "revStandaloneSettings"
# Hash: 70MFSogP5c2Um1bED6ecvQ==
*/


on mouseUp
   chooseImageFileWithDimension "appstore icon", "1024,1024"
end mouseUp
