Script "stack_revStandaloneSettings_field_id_2823"

/*
# Name: field "Custom URL Scheme" of group "Basic Application Settings" of group "Android Settings" of card "Android" of stack "revStandaloneSettings"
# ID: field id 2823 of group id 2073 of group id 2072 of card id 2060 of stack "revStandaloneSettings"
# Hash: oA5R0+GkaYs+A8Akz/5caQ==
*/


on closeField
   storeSetting "customUrlScheme", me
end closeField
