Script "stack_revStandaloneSettings_field_id_32079"

/*
# Name: field "App Tracking Transparency Message" of group "App Tracking Transparency" of group "Requirement" of card "iOS" of stack "revStandaloneSettings"
# ID: field id 32079 of group id 32083 of group id 30344 of card id 1641 of stack "revStandaloneSettings"
# Hash: mKIeaDx7ZrKNt+aUw2OOcg==
*/


on closeField
   storeSetting "AppTrackingTransparencyMessage", the text of me
end closeField
