Script "stack_revStandaloneSettings_button_id_3586"

/*
# Name: button "Splash Chooser" of group "launch-image-light-3x" of group "Splash" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 3586 of group id 3582 of group id 3538 of card id 1641 of stack "revStandaloneSettings"
# Hash: wAWa4Ovp+ZDXTft0o6ufbA==
*/


on mouseUp
   chooseImageFile the short name of the owner of me
end mouseUp
