Script "stack_revStandaloneSettings_field_id_3468"

/*
# Name: field "Bundle Id" of group "Basic Application Settings" of group "Basic Settings" of group "Basic Settings" of card "iOS" of stack "revStandaloneSettings"
# ID: field id 3468 of group id 3462 of group id 29811 of group id 30336 of card id 1641 of stack "revStandaloneSettings"
# Hash: SA0KvbP9Qx/VmtbD5Imm4w==
*/


on closeField
   storeSetting "bundle id", me
end closeField
