Script "stack_revStandaloneSettings_field_id_2228"

/*
# Name: field "Version Code" of group "Basic Application Settings" of group "Android Settings" of card "Android" of stack "revStandaloneSettings"
# ID: field id 2228 of group id 2073 of group id 2072 of card id 2060 of stack "revStandaloneSettings"
# Hash: T3V10PESOEolFds8fNmZqg==
*/


on closeField
   storeSetting "version code", me
end closeField
