Script "stack_revStandaloneSettings_field_id_1354"

/*
# Name: field "fileversion4" of group id 1348 of group "Windows" of card "Windows" of stack "revStandaloneSettings"
# ID: field id 1354 of group id 1348 of group id 1169 of card id 1016 of stack "revStandaloneSettings"
# Hash: 2PIxu+ENV1p7Z9S2Ym4l3g==
*/


on keyDown pWhich
  if pWhich is not a number then
    beep
    exit keyDown
  end if
  pass keyDown
end keyDown
