Script "stack_revStandaloneSettings_button_id_2829"

/*
# Name: button "Clear Status Bar Icon" of group "Basic Application Settings" of group "Android Settings" of card "Android" of stack "revStandaloneSettings"
# ID: button id 2829 of group id 2073 of group id 2072 of card id 2060 of stack "revStandaloneSettings"
# Hash: +XWDoAmYZz1VBY7yZCiSdg==
*/


on mouseUp
   clearSetting "statusBarIcon"
end mouseUp
