Script "stack_revStandaloneSettings_button_id_29768"

/*
# Name: button "Icon Chooser" of group "iPad Pro 12.9 Icon" of group "Icons" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 29768 of group id 29767 of group id 3494 of card id 1641 of stack "revStandaloneSettings"
# Hash: gt+cI5KCvwrDtRQu0Vu1Kg==
*/


on mouseUp
   chooseImageFileWithDimension "iPad Pro 12.9 Icon", "167,167"
end mouseUp
