Script "stack_revStandaloneSettings_field_id_2081"

/*
# Name: field "Identifier" of group "Basic Application Settings" of group "Android Settings" of card "Android" of stack "revStandaloneSettings"
# ID: field id 2081 of group id 2073 of group id 2072 of card id 2060 of stack "revStandaloneSettings"
# Hash: yzaidGV0i2mwz/HKH2R1Tg==
*/


on closeField
   storeSetting "identifier", me
end closeField

on exitField
   storeSetting "identifier", me
end exitField
