Script "stack_revStandaloneSettings_button_id_31539"

/*
# Name: button "Icon Chooser" of group "iPad Pro 11 Icon" of group "Icons" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 31539 of group id 31538 of group id 3494 of card id 1641 of stack "revStandaloneSettings"
# Hash: oSBPotRIDXOCW/teuiV2xg==
*/


on mouseUp
   chooseImageFileWithDimension "iPad Pro 11 Icon", "167,167"
end mouseUp
