Script "stack_revStandaloneSettings_button_id_2235"

/*
# Name: button "Clear Key" of group "key group" of group "Basic Application Settings" of group "Android Settings" of card "Android" of stack "revStandaloneSettings"
# ID: button id 2235 of group id 2623 of group id 2073 of group id 2072 of card id 2060 of stack "revStandaloneSettings"
# Hash: qXRUe8cvv8akuyg12kTaIg==
*/


on mouseUp
   clearSetting "key"
end mouseUp
