Script "stack_revStandaloneSettings_button_id_2827"

/*
# Name: button "Status Bar Icon Chooser" of group "Basic Application Settings" of group "Android Settings" of card "Android" of stack "revStandaloneSettings"
# ID: button id 2827 of group id 2073 of group id 2072 of card id 2060 of stack "revStandaloneSettings"
# Hash: TNZ/MUT2y4iD1cekwaxq9w==
*/


on mouseUp
   chooseImageFile "statusBarIcon"
end mouseUp
