Script "stack_revStandaloneSettings_button_id_32066"

/*
# Name: button "Splash Chooser" of group "launch-image-dark-2x" of group "Splash" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 32066 of group id 32065 of group id 3538 of card id 1641 of stack "revStandaloneSettings"
# Hash: UalM/u+Dr14Vp/mcIuXf0g==
*/


on mouseUp
   chooseImageFile the short name of the owner of me
end mouseUp

