Script "stack_revStandaloneSettings_button_id_3530"

/*
# Name: button "Icon Chooser" of group "iOS 7 Retina Icon" of group "Icons" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 3530 of group id 3529 of group id 3494 of card id 1641 of stack "revStandaloneSettings"
# Hash: 3M5yEbxyyY/DaUXTLxI1+w==
*/


on mouseUp
   chooseImageFileWithDimension "iOS 7 retina icon", "120,120"
end mouseUp
