Script "stack_revStandaloneSettings_button_id_3525"

/*
# Name: button "Icon Chooser" of group "iOS 7 iPad Icon" of group "Icons" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 3525 of group id 3524 of group id 3494 of card id 1641 of stack "revStandaloneSettings"
# Hash: VUVa7/JTNYjFSrOu6Vc3Vw==
*/


on mouseUp
   chooseImageFileWithDimension "iOS 7 ipad icon", "76,76"
end mouseUp
