Script "stack_revStandaloneSettings_button_id_3535"

/*
# Name: button "Icon Chooser" of group "iPhone 6 Plus Icon" of group "Icons" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 3535 of group id 3534 of group id 3494 of card id 1641 of stack "revStandaloneSettings"
# Hash: TwzYR4V2bH62ZNcT9IZKYQ==
*/


on mouseUp
   chooseImageFileWithDimension "iPhone 6 Plus Icon", "180,180"
end mouseUp
