Script "stack_revStandaloneSettings_button_id_29846"

/*
# Name: button "Background Fetch" of group "Background Modes" of group "Requirement" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 29846 of group id 3614 of group id 30344 of card id 1641 of stack "revStandaloneSettings"
# Hash: 4o3be06aPAWMpVp4Q6Hywg==
*/


on mouseUp
   storeSetting "background fetch", the hilite of me
end mouseUp
