Script "stack_revStandaloneSettings_field_id_3612"

/*
# Name: field "URL Name" of group id 3609 of group "Basic Settings" of group "Basic Settings" of card "iOS" of stack "revStandaloneSettings"
# ID: field id 3612 of group id 3609 of group id 29811 of group id 30336 of card id 1641 of stack "revStandaloneSettings"
# Hash: Y1UYnyHgr6yUcMQlNGIuyA==
*/


on closeField
   storeSetting "url name", the text of me
end closeField
