Script "stack_revStandaloneSettings_group_id_3599"

/*
# Name: group "Status Bar" of group id 3593 of group "Basic Settings" of group "Basic Settings" of card "iOS" of stack "revStandaloneSettings"
# ID: group id 3599 of group id 3593 of group id 29811 of group id 30336 of card id 1641 of stack "revStandaloneSettings"
# Hash: egjwA7VNokQw5TdvHuNyXQ==
*/


on mouseUp
   storeSetting "status bar hidden", the hilitedButtonName of me
end mouseUp
