Script "stack_revStandaloneSettings_button_id_31468"

/*
# Name: button "Icon Chooser" of group "iPhone X Icon" of group "Icons" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 31468 of group id 31467 of group id 3494 of card id 1641 of stack "revStandaloneSettings"
# Hash: 2XHF4mLFk/LuCUSMVjVdBw==
*/


on mouseUp
   chooseImageFileWithDimension "iPhone X Icon", "180,180"
end mouseUp
