Script "stack_revStandaloneSettings_field_id_3469"

/*
# Name: field "Bundle Version" of group "Basic Application Settings" of group "Basic Settings" of group "Basic Settings" of card "iOS" of stack "revStandaloneSettings"
# ID: field id 3469 of group id 3462 of group id 29811 of group id 30336 of card id 1641 of stack "revStandaloneSettings"
# Hash: e/SPHMYIUvC3nWd4zCnZ2g==
*/


on closeField
   storeSetting "bundle version", me
end closeField
