Script "stack_revStandaloneSettings_button_id_3827"

/*
# Name: button "Background Audio" of group "Background Modes" of group "Requirement" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 3827 of group id 3614 of group id 30344 of card id 1641 of stack "revStandaloneSettings"
# Hash: MqY/VHbqKDedfML7Mop8fg==
*/


on mouseUp
   storeSetting "background audio", the hilite of me
end mouseUp
