Script "stack_revStandaloneSettings_button_id_3826"

/*
# Name: button "beta_version" of group "Basic Application Settings" of group "Basic Settings" of group "Basic Settings" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 3826 of group id 3462 of group id 29811 of group id 30336 of card id 1641 of stack "revStandaloneSettings"
# Hash: nLCnxwHf7Cj0l/sTBvkf3g==
*/


on mouseUp
   storeSetting "beta version", the hilite of me
end mouseUp
