Script "stack_revStandaloneSettings_button_id_29844"

/*
# Name: button "Newsstand Downloads" of group "Background Modes" of group "Requirement" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 29844 of group id 3614 of group id 30344 of card id 1641 of stack "revStandaloneSettings"
# Hash: pm3OvmaBL59i//L5SEqq4g==
*/


on mouseUp
   storeSetting "background newsstand downloads", the hilite of me
end mouseUp
