Script "stack_revStandaloneSettings_button_id_32054"

/*
# Name: button "supports dark mode" of group "Basic Application Settings" of group "Basic Settings" of group "Basic Settings" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 32054 of group id 3462 of group id 29811 of group id 30336 of card id 1641 of stack "revStandaloneSettings"
# Hash: NBKJN2X6NtQ5sObMGNBkCQ==
*/


on mouseUp
   storeSetting "supports dark mode", the hilite of me
end mouseUp
