Script "stack_revStandaloneSettings_button_id_29849"

/*
# Name: button "ExAcComn" of group "Background Modes" of group "Requirement" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 29849 of group id 3614 of group id 30344 of card id 1641 of stack "revStandaloneSettings"
# Hash: Iynmod3fm+skjVJcbxKTGg==
*/


on mouseUp
   storeSetting "external acc comn", the hilite of me
end mouseUp
