Script "stack_revStandaloneSettings_field_id_3184"

/*
# Name: field "Item Group Id" of group "Samsung" of group "In App Purchasing" of group "Android Settings" of card "Android" of stack "revStandaloneSettings"
# ID: field id 3184 of group id 3182 of group id 3173 of group id 2072 of card id 2060 of stack "revStandaloneSettings"
# Hash: zAnWw8724+BiWWBt7mPeqg==
*/


on closeField
   storeSetting "samsungItemGroupId", me
end closeField
