Script "stack_revStandaloneSettings_button_id_32072"

/*
# Name: button "Splash Chooser" of group "launch-image-dark-3x" of group "Splash" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 32072 of group id 32069 of group id 3538 of card id 1641 of stack "revStandaloneSettings"
# Hash: wAWa4Ovp+ZDXTft0o6ufbA==
*/


on mouseUp
   chooseImageFile the short name of the owner of me
end mouseUp
