Script "stack_revStandaloneSettings_field_id_2825"

/*
# Name: field "Push Sender ID" of group "Basic Application Settings" of group "Android Settings" of card "Android" of stack "revStandaloneSettings"
# ID: field id 2825 of group id 2073 of group id 2072 of card id 2060 of stack "revStandaloneSettings"
# Hash: RFgLyQRNRRzBY3/6Lw+kCg==
*/


on closeField
   storeSetting "pushSenderID", me
end closeField
