Script "stack_revStandaloneSettings_button_id_2227"

/*
# Name: button "Key Chooser" of group "key group" of group "Basic Application Settings" of group "Android Settings" of card "Android" of stack "revStandaloneSettings"
# ID: button id 2227 of group id 2623 of group id 2073 of group id 2072 of card id 2060 of stack "revStandaloneSettings"
# Hash: C22dTdpRX68ukQMkNpXL1w==
*/


on mouseUp
   chooseKeyStoreFile "key"
end mouseUp
