Script "stack_revStandaloneSettings_button_id_3546"

/*
# Name: button "Splash Chooser" of group "launch-image-light-1x" of group "Splash" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 3546 of group id 3545 of group id 3538 of card id 1641 of stack "revStandaloneSettings"
# Hash: UalM/u+Dr14Vp/mcIuXf0g==
*/


on mouseUp
   chooseImageFile the short name of the owner of me
end mouseUp

