Script "stack_revStandaloneSettings_button_id_3749"

/*
# Name: button "Push Notifications" of group "Reqs" of group "Requirement" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 3749 of group id 29852 of group id 30344 of card id 1641 of stack "revStandaloneSettings"
# Hash: 799NuulGdbMu2WY7hdHmtA==
*/


on mouseUp
   storeSetting "push notifications", the hilite of me
end mouseUp
