Script "stack_revStandaloneSettings_button_id_3715"

/*
# Name: button "Local Notifications" of group "Reqs" of group "Requirement" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 3715 of group id 29852 of group id 30344 of card id 1641 of stack "revStandaloneSettings"
# Hash: CtLjvmhxF6Q/aZ1s0omiFw==
*/


on mouseUp
   storeSetting "local notifications", the hilite of me
end mouseUp
