Script "stack_revStandaloneSettings_button_id_29847"

/*
# Name: button "Acts as BT LE Acc" of group "Background Modes" of group "Requirement" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 29847 of group id 3614 of group id 30344 of card id 1641 of stack "revStandaloneSettings"
# Hash: h97WdjYcjf/DSIbi8SOBHg==
*/


on mouseUp
   storeSetting "acts as bt le", the hilite of me
end mouseUp
