Script "stack_revStandaloneSettings_field_id_29809"

/*
# Name: field "Build Number" of group "Basic Application Settings" of group "Basic Settings" of group "Basic Settings" of card "iOS" of stack "revStandaloneSettings"
# ID: field id 29809 of group id 3462 of group id 29811 of group id 30336 of card id 1641 of stack "revStandaloneSettings"
# Hash: HdYetL1vek6t9GJM3bob+A==
*/


on closeField
   storeSetting "bundle build", me
end closeField
