Script "stack_revStandaloneSettings_group_id_2246"

/*
# Name: group "Status Bar" of group "User Interface Options" of group "Android Settings" of card "Android" of stack "revStandaloneSettings"
# ID: group id 2246 of group id 2238 of group id 2072 of card id 2060 of stack "revStandaloneSettings"
# Hash: egjwA7VNokQw5TdvHuNyXQ==
*/


on mouseUp
   storeSetting "status bar hidden", the hilitedButtonName of me
end mouseUp
