Script "stack_revStandaloneSettings_button_id_3741"

/*
# Name: button "Fontmap Chooser" of group "Fontmap file" of group id 3734 of group "Basic Settings" of group "Basic Settings" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 3741 of group id 3739 of group id 3734 of group id 29811 of group id 30336 of card id 1641 of stack "revStandaloneSettings"
# Hash: Th/5CVQmu530Dt1wAy6ciw==
*/


on mouseUp
   chooseFontMapFile
end mouseUp
