Script "stack_revStandaloneSettings_button_id_29843"

/*
# Name: button "Location Update" of group "Background Modes" of group "Requirement" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 29843 of group id 3614 of group id 30344 of card id 1641 of stack "revStandaloneSettings"
# Hash: 2jRfPPtxesZ/IjcYSi54qg==
*/


on mouseUp
   storeSetting "background location update", the hilite of me
end mouseUp
