Script "stack_revStandaloneSettings_button_id_3519"

/*
# Name: button "Icon Chooser" of group "iOS 7 iPad Retina Icon" of group "Icons" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 3519 of group id 3518 of group id 3494 of card id 1641 of stack "revStandaloneSettings"
# Hash: cBc+k0R5R9uKaz/1MmPmfw==
*/


on mouseUp
   chooseImageFileWithDimension "iOS 7 ipad retina icon", "152,152"
end mouseUp
