Script "stack_revStandaloneSettings_group_id_2090"

/*
# Name: group "Externals" of group "Basic Application Settings" of group "Android Settings" of card "Android" of stack "revStandaloneSettings"
# ID: group id 2090 of group id 2073 of group id 2072 of card id 2060 of stack "revStandaloneSettings"
# Hash: lf4Lmo2D1oQ1FJO8/cFaOQ==
*/


on mouseUp
   storeSetting ("include" && the short name of the target), the hilite of the target
end mouseUp
