Script "stack_revStandaloneSettings_button_id_31499"

/*
# Name: button "NFC Tag Reading" of group "Application Permissions" of group "Android Settings" of card "Android" of stack "revStandaloneSettings"
# ID: button id 31499 of group id 2352 of group id 2072 of card id 2060 of stack "revStandaloneSettings"
# Hash: OnokUV0Dwc35E9vkKLc6Uw==
*/


on mouseUp
   storeSetting "nfc", the hilited of me
end mouseUp
