Script "stack_revStandaloneSettings_button_id_3515"

/*
# Name: button "Icon Chooser" of group "iPad Retina Icon" of group "Icons" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 3515 of group id 3514 of group id 3494 of card id 1641 of stack "revStandaloneSettings"
# Hash: uXjfWAPOYeA20ZM7qHfqJw==
*/


on mouseUp
   chooseImageFileWithDimension "ipad retina icon", "144,144"
end mouseUp
