Script "stack_revStandaloneSettings_field_id_3192"

/*
# Name: field "Store Key" of group "Google" of group "In App Purchasing" of group "Android Settings" of card "Android" of stack "revStandaloneSettings"
# ID: field id 3192 of group id 3190 of group id 3173 of group id 2072 of card id 2060 of stack "revStandaloneSettings"
# Hash: xWgurO9yOC75ctcgNceXOQ==
*/


on closeField
   storeSetting "storeKey", me
end closeField
