Script "stack_revStandaloneSettings_field_id_3467"

/*
# Name: field "Display Name" of group "Basic Application Settings" of group "Basic Settings" of group "Basic Settings" of card "iOS" of stack "revStandaloneSettings"
# ID: field id 3467 of group id 3462 of group id 29811 of group id 30336 of card id 1641 of stack "revStandaloneSettings"
# Hash: ZA/ZAFs6RNnVOXyhTubodw==
*/


on closeField
   storeSetting "display name", the text of me
end closeField
