Script "stack_revStandaloneSettings_field_id_2082"

/*
# Name: field "Version Name" of group "Basic Application Settings" of group "Android Settings" of card "Android" of stack "revStandaloneSettings"
# ID: field id 2082 of group id 2073 of group id 2072 of card id 2060 of stack "revStandaloneSettings"
# Hash: 7a/id4r2XZRUleCXT1Mt2Q==
*/


on closeField
   storeSetting "version name", me
end closeField
