Script "stack_revStandaloneSettings_field_id_2080"

/*
# Name: field "Label" of group "Basic Application Settings" of group "Android Settings" of card "Android" of stack "revStandaloneSettings"
# ID: field id 2080 of group id 2073 of group id 2072 of card id 2060 of stack "revStandaloneSettings"
# Hash: wxwDP86kR0Qk1iDc1mNOiw==
*/


on closeField
   storeSetting "label", the text of me
end closeField
