Script "stack_revStandaloneSettings_button_id_3816"

/*
# Name: button "Hardware Accelerated" of group "Basic Application Settings" of group "Android Settings" of card "Android" of stack "revStandaloneSettings"
# ID: button id 3816 of group id 2073 of group id 2072 of card id 2060 of stack "revStandaloneSettings"
# Hash: FLZIJ5OqjzMq60qlMpyLyw==
*/


on mouseUp
   storeSetting "hardware accelerated", the hilited of me
end mouseUp
