Script "stack_revStandaloneSettings_group_id_3720"

/*
# Name: group "Location Auth Type" of group "location auth" of group "Requirement" of card "iOS" of stack "revStandaloneSettings"
# ID: group id 3720 of group id 3717 of group id 30344 of card id 1641 of stack "revStandaloneSettings"
# Hash: 1dEmOGZgNoaQiZRF/rxXWQ==
*/


on mouseUp
   storeSetting "location auth type", the hilitedButtonName of me
end mouseUp
