Script "stack_revStandaloneSettings_group_id_3473"

/*
# Name: group "Externals" of group "Basic Application Settings" of group "Basic Settings" of group "Basic Settings" of card "iOS" of stack "revStandaloneSettings"
# ID: group id 3473 of group id 3462 of group id 29811 of group id 30336 of card id 1641 of stack "revStandaloneSettings"
# Hash: lf4Lmo2D1oQ1FJO8/cFaOQ==
*/


on mouseUp
   storeSetting ("include" && the short name of the target), the hilite of the target
end mouseUp
