Script "stack_revStandaloneSettings_button_id_29851"

/*
# Name: button "Remote Notifications" of group "Background Modes" of group "Requirement" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 29851 of group id 3614 of group id 30344 of card id 1641 of stack "revStandaloneSettings"
# Hash: IB0y0zjVPaB80ujCR1t7nQ==
*/


on mouseUp
   storeSetting "remote notifications", the hilite of me
end mouseUp
