Script "stack_revStandaloneSettings_button_id_3550"

/*
# Name: button "Splash Chooser" of group "launch-image-light-2x" of group "Splash" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 3550 of group id 3549 of group id 3538 of card id 1641 of stack "revStandaloneSettings"
# Hash: UalM/u+Dr14Vp/mcIuXf0g==
*/


on mouseUp
   chooseImageFile the short name of the owner of me
end mouseUp

