Script "stack_revStandaloneSettings_button_id_3742"

/*
# Name: button "Clear fontmap" of group "Fontmap file" of group id 3734 of group "Basic Settings" of group "Basic Settings" of card "iOS" of stack "revStandaloneSettings"
# ID: button id 3742 of group id 3739 of group id 3734 of group id 29811 of group id 30336 of card id 1641 of stack "revStandaloneSettings"
# Hash: ZNCvWseOgQHcY6mke1LDGQ==
*/


on mouseUp
   clearSetting "fontmappings"
end mouseUp
