Script "stack_revOnline_button_id_3529735"

/*
# Name: button "Cancel" of group "external upload" of group "chooser" of group "stack" of group "viewing pane" of card "main" of stack "revOnline"
# ID: button id 3529735 of group id 937669 of group id 937645 of group id 31860 of group id 31859 of card id 1002 of stack "revOnline"
# Hash: 44aKSBU1r8rl0iySOkPpJQ==
*/


on mouseUp
   discardChanges
end mouseUp
