Script "stack_revOnline_group_id_354435"

/*
# Name: group "Slider" of group "viewing pane scrollbar" of card "main" of stack "revOnline"
# ID: group id 354435 of group id 354433 of card id 1002 of stack "revOnline"
# Hash: /E2lWyDGbdeHXho8OKrrZg==
*/


on mouseEnter
  set the hilite of button "slider_icon" of me to true
  pass mouseEnter
end mouseEnter

on mouseLeave
  set the hilite of button "slider_icon" of me to false
  pass mouseLeave
end mouseLeave
