Script "stack_revOnline_group_id_327467"

/*
# Name: group "Slider" of group "search list scrollbar" of card "main" of stack "revOnline"
# ID: group id 327467 of group id 327465 of card id 1002 of stack "revOnline"
# Hash: /E2lWyDGbdeHXho8OKrrZg==
*/


on mouseEnter
  set the hilite of button "slider_icon" of me to true
  pass mouseEnter
end mouseEnter

on mouseLeave
  set the hilite of button "slider_icon" of me to false
  pass mouseLeave
end mouseLeave
