Script "stack_com.livecode.pi.colorwithalpha_scrollbar_id_1011"

/*
# Name: scrollbar "Scrollbar" of group id 1012 of group "template" of card id 1002 of stack "com.livecode.pi.colorwithalpha"
# ID: scrollbar id 1011 of group id 1012 of group id 1009 of card id 1002 of stack "com.livecode.pi.colorwithalpha"
# Hash: mfzH1MQLDCACb9BTkNhbTw==
*/


on scrollbarDrag
   dispatch "valueChanged"
end scrollbarDrag
