Script "stack_revObjectProperties_bkgnd_id_1031"

/*
# Name: bkgnd "Other Properties" of stack "revObjectProperties" of stack "revSearch"
# ID: bkgnd id 1031 of stack "revObjectProperties" of stack "revSearch"
# Hash: 5bkIHu5HwrKXhv3u1JkYSQ==
*/


on mouseUp
  if the hilite of btn "specific property" is true then enable btn "specific property selector"
  else disable btn "specific property selector"
end mouseUp
