Script "stack_DataGridsTour_button_id_18847"

/*
# Name: button "step2" of card "Table" of stack "DataGridsTour"
# ID: button id 18847 of card id 5536 of stack "DataGridsTour"
# Hash: /MNuR4WaKq+kZKZYVB2x5A==
*/


on mouseUp
   lock screen
   resetDemonstration
   
   ## These action handlers can be found in the card script 
   columnsSetNames
   loadData
   
   stepSet 2
   unlock screen
end mouseUp
