Script "stack_DataGridsTour_button_id_18849"

/*
# Name: button "step3" of card "Table" of stack "DataGridsTour"
# ID: button id 18849 of card id 5536 of stack "DataGridsTour"
# Hash: NyYOr7V2FdFUvzjexVcOtA==
*/


on mouseUp
   lock screen
   resetDemonstration
   
   ## These action handlers can be found in the card script 
   columnsSetNames
   loadData
   columnsSetLook
   
   stepSet 3
   unlock screen
end mouseUp
