Script "stack_revSETemplate_button_id_51607"

/*
# Name: button "Breakpoint Context Menu" of group "Gutter" of group "Editor" of card "Main" of stack "revSETemplate" of stack "revNewScriptEditor"
# ID: button id 51607 of group id 3333 of group id 1046 of card id 1002 of stack "revSETemplate" of stack "revNewScriptEditor"
# Hash: kPNYamrm2lmD/c09+9OXUw==
*/


on mouseDown
end mouseDown

on mouseUp
end mouseUp




