Script "stack_revNewScriptEditor_1_button_id_14918"

/*
# Name: button "Previous" of group "Interactive Find" of group "Editor" of card "Main" of stack "revNewScriptEditor 1" of stack "revNewScriptEditor"
# ID: button id 14918 of group id 14913 of group id 1046 of card id 1002 of stack "revNewScriptEditor 1" of stack "revNewScriptEditor"
# Hash: Ld/NmtaDsNC9cbK1sCgomw==
*/


on mouseUp
  iFindPrevious
end mouseUp

on mouseDoubleUp
  iFindPrevious
end mouseDoubleUp

