Script "stack_revNewScriptEditor_1_button_id_14917"

/*
# Name: button "Next" of group "Interactive Find" of group "Editor" of card "Main" of stack "revNewScriptEditor 1" of stack "revNewScriptEditor"
# ID: button id 14917 of group id 14913 of group id 1046 of card id 1002 of stack "revNewScriptEditor 1" of stack "revNewScriptEditor"
# Hash: 86vNq0JWPw5WySX2oTOMQw==
*/


on mouseUp
  iFindNext false
end mouseUp

on mouseDoubleUp
  iFindNext false
end mouseDoubleUp

