Script "stack_revNewScriptEditor_1_button_id_55114"

/*
# Name: button "Update" of group "Breakpoints" of group "Panes" of card "Main" of stack "revNewScriptEditor 1" of stack "revNewScriptEditor"
# ID: button id 55114 of group id 54992 of group id 1050 of card id 1002 of stack "revNewScriptEditor 1" of stack "revNewScriptEditor"
# Hash: wGX1TVos5KqpsRAa2FUSwQ==
*/


on mouseUp
   update
end mouseUp
