Script "stack_revSETemplate_button_id_14915"

/*
# Name: button "Close" of group "Interactive Find" of group "Editor" of card "Main" of stack "revSETemplate" of stack "revNewScriptEditor"
# ID: button id 14915 of group id 14913 of group id 1046 of card id 1002 of stack "revSETemplate" of stack "revNewScriptEditor"
# Hash: oQrDCQxaZEgEHFSXcfKttA==
*/


on mouseUp
  findFinalize
  hideInteractiveFind
end mouseUp
