Script "stack_revSETemplate_button_id_1019"

/*
# Name: button "Redo" of group "Toolbar" of card "Main" of stack "revSETemplate" of stack "revNewScriptEditor"
# ID: button id 1019 of group id 1021 of card id 1002 of stack "revSETemplate" of stack "revNewScriptEditor"
# Hash: Cy1waGk25fYFRyte+kpacw==
*/


on mouseUp
   actionRedo
     # Performing an redo may enable the undo button
   update
end mouseUp
