Script "stack_revSETemplate_card_id_1002"

/*
# Name: card "Main" of stack "revSETemplate" of stack "revNewScriptEditor"
# ID: card id 1002 of stack "revSETemplate" of stack "revNewScriptEditor"
# Hash: Z4VYi5ipDmD/wRxTJwDwpw==
*/


# OK-2008-06-24 : The IDE periodically sends this message to the current card of the script editor,
# so it should be handled to prevent errors.
command revUpdatePalette
end revUpdatePalette
