Script "stack_revSETemplate_button_id_1018"

/*
# Name: button "Undo" of group "Toolbar" of card "Main" of stack "revSETemplate" of stack "revNewScriptEditor"
# ID: button id 1018 of group id 1021 of card id 1002 of stack "revSETemplate" of stack "revNewScriptEditor"
# Hash: pEod5DCbMr2bHzBXyA+sPw==
*/


on mouseUp
   actionUndo
   # Performing an undo may enable the redo button
   update
end mouseUp
