Script "stack_revPlugInEditor_button_id_1056"

/*
# Name: button "chosen" of group "Load:" of group "Open plugin:" of card id 1002 of stack "revPlugInEditor"
# ID: button id 1056 of group id 1027 of group id 1076 of card id 1002 of stack "revPlugInEditor"
# Hash: GFAMcdXIUqvDPBjzDJsyWw==
*/


on mouseUp
  hilite btn "Include in Plug-ins menu"
  disable btn "Include in Plug-ins menu"
  pass mouseUp
end mouseUp
