Script "stack_revPlugInEditor_button_id_1057"

/*
# Name: button "startup" of group "Load:" of group "Open plugin:" of card id 1002 of stack "revPlugInEditor"
# ID: button id 1057 of group id 1027 of group id 1076 of card id 1002 of stack "revPlugInEditor"
# Hash: TZIkzABmTxdj9YaldHqE7Q==
*/


on mouseUp
  hilite btn "Include in Plug-ins menu"
  enable btn "Include in Plug-ins menu"
  send "mouseUp" to btn "Include in Plug-ins menu"
  pass mouseUp
end mouseUp
