Script "stack_revResourceCenter_field_id_578844"

/*
# Name: field "Number" of group "Example" of group id 578850 of group "mainContent" of card "Repeatingastringoftext" of stack "revResourceCenter"
# ID: field id 578844 of group id 578841 of group id 578850 of group id 109247 of card id 109229 of stack "revResourceCenter"
# Hash: TVpJAwV0Q30nC6YfDRvSCQ==
*/


on keyDown theKey
  if theKey is not a number then beep
  else pass keyDown
end keyDown
