Script "stack_revResourceCenter_group_id_577015"

/*
# Name: group "Example" of group id 584247 of group "mainContent" of card "SortingAList" of stack "revResourceCenter"
# ID: group id 577015 of group id 584247 of group id 113786 of card id 113772 of stack "revResourceCenter"
# Hash: wWO5VcL0CorxpAARrOrOsA==
*/


on preOpenBackGround
  put the defaultTitlesList of field "Example Titles" into field "Example Titles"
end preOpenBackGround
