Script "stack_revResourceCenter_scrollbar_id_579803"

/*
# Name: scrollbar "Red" of group "Example" of group id 579804 of group "mainContent" of card "SettinganRGBcolorchannelofanobject" of stack "revResourceCenter"
# ID: scrollbar id 579803 of group id 577022 of group id 579804 of group id 80407 of card id 80392 of stack "revResourceCenter"
# Hash: Q/VbgnxsEHSXq7tdUsFtFw==
*/


on scrollbarDrag newPosition
  set the redChannel of graphic "Color Swatch" to newPosition
end scrollbarDrag
