Script "stack_revResourceCenter_group_id_578773"

/*
# Name: group "Example" of group id 571863 of group "mainContent" of card "Limitingthenumberofcharactersduringdataentry" of stack "revResourceCenter"
# ID: group id 578773 of group id 571863 of group id 80363 of card id 80353 of stack "revResourceCenter"
# Hash: 7P0OWQBy523OQefN7Mn8yA==
*/


on openBackGround
  put empty into field "Example"
  select text of field "Example"
end openBackGround
