Script "stack_revResourceCenter_group_id_578841"

/*
# Name: group "Example" of group id 578850 of group "mainContent" of card "Repeatingastringoftext" of stack "revResourceCenter"
# ID: group id 578841 of group id 578850 of group id 109247 of card id 109229 of stack "revResourceCenter"
# Hash: 28BnRlynbTLUCYQtcL8Aqg==
*/


on preOpenBackground
  put empty into field "String"
  put empty into field "Number"
  put empty into field "Result"
end preOpenBackground
