Script "stack_revResourceCenter_group_id_577049"

/*
# Name: group "Example" of group id 584271 of group "mainContent" of card "convertinganabsolutepathtoarelativepath" of stack "revResourceCenter"
# ID: group id 577049 of group id 584271 of group id 104792 of card id 104775 of stack "revResourceCenter"
# Hash: ArR2XEyLWrITzux78kclDg==
*/


on preOpenBackground
  put empty into field "Path"
  put the defaultFolder into field "Starting Folder"
end preOpenBackground
