Script "stack_revResourceCenter_button_id_579855"

/*
# Name: button "Window" of group "Menubar" of group "Example" of group id 584259 of group "mainContent" of card "Updatingamenuwithalistofopenwindows" of stack "revResourceCenter"
# ID: button id 579855 of group id 579854 of group id 577034 of group id 584259 of group id 100298 of card id 100278 of stack "revResourceCenter"
# Hash: z2Cj1WSjjCy76Twp014AJA==
*/


on menuPick theItem
  answer "You chose:" & return & tab & theItem
end menuPick 
