Script "stack_revResourceCenter_scrollbar_id_579802"

/*
# Name: scrollbar "Blue" of group "Example" of group id 579804 of group "mainContent" of card "SettinganRGBcolorchannelofanobject" of stack "revResourceCenter"
# ID: scrollbar id 579802 of group id 577022 of group id 579804 of group id 80407 of card id 80392 of stack "revResourceCenter"
# Hash: xZ8+axzVoltgnlVrIawAYA==
*/


on scrollbarDrag newPosition
  set the blueChannel of graphic "Color Swatch" to newPosition
end scrollbarDrag
