Script "stack_revResourceCenter_field_id_578779"

/*
# Name: field "Digits Only" of group "Example" of group id 571864 of group "mainContent" of card "Acceptingonlydigitcharactersduringdataentry" of stack "revResourceCenter"
# ID: field id 578779 of group id 578778 of group id 571864 of group id 80390 of card id 80380 of stack "revResourceCenter"
# Hash: TVpJAwV0Q30nC6YfDRvSCQ==
*/


on keyDown theKey
  if theKey is not a number then beep
  else pass keyDown
end keyDown
