Script "stack_revResourceCenter_group_id_577029"

/*
# Name: group "Example" of group id 579841 of group "mainContent" of card "Textmenu:populatingwithcontent" of stack "revResourceCenter"
# ID: group id 577029 of group id 579841 of group id 82665 of card id 82654 of stack "revResourceCenter"
# Hash: Yq6MUUSawDTH5XJdCDsEfA==
*/


on openBackGround
  put "(Click the Populate Menu button first" into button "Text"
end openBackGround
