Script "stack_revResourceCenter_group_id_577046"

/*
# Name: group "Example" of group id 584269 of group "mainContent" of card "Displayingacountdown(non-blocking)" of stack "revResourceCenter"
# ID: group id 577046 of group id 584269 of group id 80225 of card id 80215 of stack "revResourceCenter"
# Hash: 0AVXIxRCj1Y7XIHVv98UTQ==
*/


on closeBackGround
  if "displayCurrentVerse" is in the pendingMessages then send "mouseUp" to button "Example"
end closeBackGround
