Script "stack_revResourceCenter_group_id_577038"

/*
# Name: group "Example" of group id 579871 of group "mainContent" of card "Speakinganalertmessage" of stack "revResourceCenter"
# ID: group id 577038 of group id 579871 of group id 100222 of card id 100210 of stack "revResourceCenter"
# Hash: zeVS/V9hAxxbYNOauXZy8A==
*/


on preOpenBackground
  put the defaultAlert of field "Speech" into field "Speech"
end preOpenBackground
