Script "stack_revResourceCenter_group_id_578792"

/*
# Name: group "Example" of group id 578797 of group "mainContent" of card "Insertinglinebreakstohardwraptext" of stack "revResourceCenter"
# ID: group id 578792 of group id 578797 of group id 80450 of card id 80438 of stack "revResourceCenter"
# Hash: W7pDss21YxKRhZsCKs3/yA==
*/


on preOpenBackground
  put the originalText of field "Example Text" into field "Example Text"
  put "30" into field "Line Length"
end preOpenBackground
