Script "stack_revResourceCenter_field_id_540877"

/*
# Name: field "Label" of group "Right" of group "Actions" of bkgnd "group id 2127" of stack "revResourceCenter"
# ID: field id 540877 of group id 540875 of group id 540871 of bkgnd id 2127 of stack "revResourceCenter"
# Hash: 3ofPoKCFEth7ppop3v+WJA==
*/


on mouseEnter
   set the foregroundColor of me to "124,193,222"
end mouseEnter

on mouseLeave
   set the foregroundColor of me to "50,50,50"
end mouseLeave
