Script "stack_revResourceCenter_group_id_577043"

/*
# Name: group "Example" of group id 579883 of group "mainContent" of card "Printingallcardsthatcontainaword" of stack "revResourceCenter"
# ID: group id 577043 of group id 579883 of group id 77997 of card id 77987 of stack "revResourceCenter"
# Hash: tPpyVSLU4dXMYlxzNkfj9g==
*/


on openBackGround
  set the defaultStack to the topStack
end openBackGround
