Script "stack_revResourceCenter_group_id_579783"

/*
# Name: group "Example" of group id 579796 of group "mainContent" of card "Dragdropabackgroundcolorontoanobject" of stack "revResourceCenter"
# ID: group id 579783 of group id 579796 of group id 80325 of card id 80305 of stack "revResourceCenter"
# Hash: aMzTFOj7SbKrDCyxzVuy1A==
*/


on preOpenBackground
  set the backgroundColor of graphic "Ball" to empty
  set the label of graphic "Ball" to empty
end preOpenBackground
