Script "stack_revResourceCenter_group_id_577048"

/*
# Name: group "Example" of group id 579908 of group "mainContent" of card "Convertingarelativepathtoanabsolutepath" of stack "revResourceCenter"
# ID: group id 577048 of group id 579908 of group id 102592 of card id 102575 of stack "revResourceCenter"
# Hash: ArR2XEyLWrITzux78kclDg==
*/


on preOpenBackground
  put empty into field "Path"
  put the defaultFolder into field "Starting Folder"
end preOpenBackground
