Script "stack_revResourceCenter_group_id_578803"

/*
# Name: group "Example" of group id 578809 of group "mainContent" of card "InsertingSomeTextBeforeEachLineinaField" of stack "revResourceCenter"
# ID: group id 578803 of group id 578809 of group id 100260 of card id 100240 of stack "revResourceCenter"
# Hash: v9zS87NbJvdKW0Ham4t1cA==
*/


on preOpenBackground
  put empty into field "Prefix"
  put empty into field "List"
  select text of field "Prefix"
end preOpenBackground
