Script "stack_revResourceCenter_field_id_578774"

/*
# Name: field "Example" of group "Example" of group id 571863 of group "mainContent" of card "Limitingthenumberofcharactersduringdataentry" of stack "revResourceCenter"
# ID: field id 578774 of group id 578773 of group id 571863 of group id 80363 of card id 80353 of stack "revResourceCenter"
# Hash: DpkomuKH5wrKWud9UkzfCg==
*/


on keyDown theKey
  if the length of me >= 5 then beep
  else pass keyDown
end keyDown
