Script "stack_revResourceCenter_group_id_577051"

/*
# Name: group "Example" of group id 580784 of group "mainContent" of card "Convertingbetweencharactersandnumerical(ASCII)values" of stack "revResourceCenter"
# ID: group id 577051 of group id 580784 of group id 113648 of card id 109268 of stack "revResourceCenter"
# Hash: R/gwcgFbpPVyyiMkJhaLVg==
*/


on returnInField
  enterInField
end returnInField

on enterInField
  send "mouseUp" to button "Convert"
end enterInField
