Script "stack_revResourceCenter_button_id_579872"

/*
# Name: button "Center Me!" of group "Example" of group id 584263 of group "mainContent" of card "Centeringawindowonthescreen" of stack "revResourceCenter"
# ID: button id 579872 of group id 577039 of group id 584263 of group id 80282 of card id 80273 of stack "revResourceCenter"
# Hash: rr4lPlTAayqWqSBkvWgjmg==
*/


on mouseUp
  centerMe
end mouseUp

on centerMe
  set the loc of this stack to the screenLoc
end centerMe
