Script "stack_revResourceCenter_group_id_577024"

/*
# Name: group "Example" of group id 579813 of group "mainContent" of card "Gettingthedimensionsofapicturefile" of stack "revResourceCenter"
# ID: group id 577024 of group id 579813 of group id 80351 of card id 80339 of stack "revResourceCenter"
# Hash: jeMAFJ1ujkoA7dGOqTUTSg==
*/


on preOpenBackground
  put empty into field "Filename"
  put "??" into word 2 of field "Height"
  put "??" into word 2 of field "Width"
end preOpenBackground
