Script "stack_revResourceCenter_scrollbar_id_579801"

/*
# Name: scrollbar "Green" of group "Example" of group id 579804 of group "mainContent" of card "SettinganRGBcolorchannelofanobject" of stack "revResourceCenter"
# ID: scrollbar id 579801 of group id 577022 of group id 579804 of group id 80407 of card id 80392 of stack "revResourceCenter"
# Hash: f4dBtaGLxtng4F86DDazWw==
*/


on scrollbarDrag newPosition
  set the greenChannel of graphic "Color Swatch" to newPosition
end scrollbarDrag
