Script "stack_revResourceCenter_button_id_579850"

/*
# Name: button "Font" of group "Example" of group id 579852 of group "mainContent" of card "Placingafontlistintoamenu" of stack "revResourceCenter"
# ID: button id 579850 of group id 577033 of group id 579852 of group id 100342 of card id 100330 of stack "revResourceCenter"
# Hash: yJ1M6IfVpEdiSAXQtv9rjw==
*/


on menuPick theItem
  answer "You chose" && quote & theItem & quote & "."
end menuPick
