Script "stack_revResourceCenter_button_id_579839"

/*
# Name: button "Text" of group "Example" of group id 579841 of group "mainContent" of card "Textmenu:populatingwithcontent" of stack "revResourceCenter"
# ID: button id 579839 of group id 577029 of group id 579841 of group id 82665 of card id 82654 of stack "revResourceCenter"
# Hash: EcaUvbQKDQP7QbgIOEelkw==
*/


on menuPick theItem
  answer "You chose:" & return & tab & theItem
end menuPick
