Script "stack_revResourceCenter_button_id_577054"

/*
# Name: button "Say Hello" of group "Example" of group id 582516 of group "mainContent" of card "Display"HelloWorld"" of stack "revResourceCenter"
# ID: button id 577054 of group id 577001 of group id 582516 of group id 91455 of card id 91444 of stack "revResourceCenter"
# Hash: HzfzF4ZCbZ8XCDMn0yxCwQ==
*/


on mouseUp
  answer "Hello world!"
end mouseUp
