Script "stack_rTreeEngine_button_id_2621"

/*
# Name: button "columnHeaderBehavior" of card "Engine" of stack "rTreeEngine" of stack "livecodeTestInterface"
# ID: button id 2621 of card id 2151 of stack "rTreeEngine" of stack "livecodeTestInterface"
# Hash: xH1Fj/LebK3mMHgU0EWaKw==
*/


local 

on renderColumnHeader tData
   -- beep
   -- put tData[name] ###
   -- set the name of me to tData[name]
end renderColumnHeader

on mouseUp
   
end mouseUp
