Script "stack_revTitleBarSelector_button_id_1022"

/*
# Name: button "title,menu,maximize,close" of bkgnd "decorations" of stack "revTitleBarSelector" of stack "com.livecode.pi.decorations"
# ID: button id 1022 of bkgnd id 1011 of stack "revTitleBarSelector" of stack "com.livecode.pi.decorations"
# Hash: /gRpYp9h98YBmmsXaLKEng==
*/


on mouseUp
  set the cReturnValue of this stack to "title,menu,maximize"
  pass mouseUp
end mouseUp

on mouseDoubleUp
  pass mouseDoubleUp
end mouseDoubleUp
