Script "stack_revTitleBarSelector_button_id_1027"

/*
# Name: button "title,menu" of bkgnd "decorations" of stack "revTitleBarSelector" of stack "com.livecode.pi.decorations"
# ID: button id 1027 of bkgnd id 1011 of stack "revTitleBarSelector" of stack "com.livecode.pi.decorations"
# Hash: 6UMRUSaqkc688ZU7AYqkag==
*/


on mouseUp
  set the cReturnValue of this stack to "title,menu"
  pass mouseUp
end mouseUp

on mouseDoubleUp
  pass mouseDoubleUp
end mouseDoubleUp
