Script "stack_revTitleBarSelector_button_id_1021"

/*
# Name: button "default" of bkgnd "decorations" of stack "revTitleBarSelector" of stack "com.livecode.pi.decorations"
# ID: button id 1021 of bkgnd id 1011 of stack "revTitleBarSelector" of stack "com.livecode.pi.decorations"
# Hash: VyvVIyZ7ZkfJ/0tnMRr2eg==
*/


on mouseUp
  set the cReturnValue of this stack to "default"
  pass mouseUp
end mouseUp

on mouseDoubleUp
  pass mouseDoubleUp
end mouseDoubleUp

