Script "stack_revTitleBarSelector_button_id_1023"

/*
# Name: button "title,menu,maximize" of bkgnd "decorations" of stack "revTitleBarSelector" of stack "com.livecode.pi.decorations"
# ID: button id 1023 of bkgnd id 1011 of stack "revTitleBarSelector" of stack "com.livecode.pi.decorations"
# Hash: +7/s0r0hSf7tJ/WlY5z72A==
*/


on mouseUp
  set the cReturnValue of this stack to "title,menu,minimize"
  pass mouseUp
end mouseUp

on mouseDoubleUp
  pass mouseDoubleUp
end mouseDoubleUp
