Script "stack_revTitleBarSelector_button_id_1029"

/*
# Name: button "empty" of bkgnd "decorations" of stack "revTitleBarSelector" of stack "com.livecode.pi.decorations"
# ID: button id 1029 of bkgnd id 1011 of stack "revTitleBarSelector" of stack "com.livecode.pi.decorations"
# Hash: E9Y6jKqbdqK9iGwb03+m5g==
*/


on mouseUp
  set the cReturnValue of this stack to "empty"
  pass mouseUp
end mouseUp

on mouseDoubleUp
  pass mouseDoubleUp
end mouseDoubleUp
