Script "stack_revTitleBarSelector_button_id_1025"

/*
# Name: button "title,menu,minimize" of bkgnd "decorations" of stack "revTitleBarSelector" of stack "com.livecode.pi.decorations"
# ID: button id 1025 of bkgnd id 1011 of stack "revTitleBarSelector" of stack "com.livecode.pi.decorations"
# Hash: asjMDeJNIcdN64TtnbO1Pw==
*/


on mouseUp
  set the cReturnValue of this stack to "title"
  pass mouseUp
end mouseUp

on mouseDoubleUp
  pass mouseDoubleUp
end mouseDoubleUp
